ipynb-filters: [nbdev_filter]
link-external-newwindow: true

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme:
      light: [cosmo, style-light.scss]
      dark: [darkly, style-dark.scss]

    max-width: 100%
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "blurr"
  site-url: "https://ohmeow.github.io/blurr/"
  description: "A library designed for fastai developers who want to train and deploy Hugging Face transformers"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/ohmeow/blurr/tree/master/"
  repo-actions: [issue]
  navbar:
    pinned: true
   
    search: true
    right:
      - icon: github
        href: "https://github.com/ohmeow/blurr/tree/master/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
