repository: ohmeow/blurr
output: web
topnav_title: blurr
default_badges: {colab: true}
site_title: blurr
company_name: ohmeow
description: Writing a library entirely in notebooks
google_search: e68be77d589bc243c
use_math: true
google_analytics:
twitter_username: waydegilliam

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered.

exclude:
  - .idea/
  - .gitignore
  - vendor
 
exclude: [vendor]

default_badges:
  colab: false

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars: [home_sidebar]
baseurl: /blurr/
plugins:
    - jekyll-remote-theme
    
remote_theme: fastai/nbdev-jekyll-theme
